[tool.poetry]
name = "storefront"
version = "0.1.0"
description = "django tutorial"
authors = ["andre361 <joeydre69@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
